steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/${_ANALYTICS_PROJECT}/${_IMAGE_NAME}', '.']
  dir: /workspace/app

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/${_ANALYTICS_PROJECT}/${_IMAGE_NAME}']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
       sed -e "s/\$$PROJECT_ID/$_ANALYTICS_PROJECT/g" \
           -e "s/\$$ML_MODELS_BUCKET/$$ML_MODELS_BUCKET/g" workflow.yaml.tmpl > workflow.yaml
  dir: /workspace/conf

- name: 'eu.gcr.io/${PROJECT_ID}/kubeflow-tools'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
       python3 /workspace/bin/kfp_deploy.py ${_KUBEFLOW_HOST} "${REPO_NAME}-${SHORT_SHA}" /workspace/conf/workflow.yaml

substitutions:
  _IMAGE_NAME: train-iris

options:
  env:
  - ML_MODELS_BUCKET=${_ANALYTICS_PROJECT}-models

timeout: 1800s
